name: Ansible Playbook
on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    runs-on: ubuntu-latest  
    steps:
    - name: Git Clone repo
      uses: actions/checkout@v1
       
    - id: host
      env:
        SSH: ${{ secrets.KEY }}
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
          echo "$SSH" > ansible/wl.pem
          chmod 400 ansible/wl.pem
          cat ansible/wl.pem
          echo "$PRIVATE_KEY" > id_rsa
          cat id_rsa
                      
    - name: Run Ansible-playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/lesson12.yml'
        inventoryFile: 'ansible/hosts'
        keyFile: "ansible/wl.pem"
